
services:
    twig.extension.pretty_print:
        class: RedpillLinpro\NosqlBundle\Extension\TwigExtensionPrettyPrint
        tags:
            - { name: 'twig.extension' }

    property_accessor:
      class: %property_accessor.class%
      arguments: [true]
